### PR TITLE
GCC colourization fix and conf files for `mount' and `df'

### PR DESCRIPTION
**Pull request by emanueleaina**
Hello,
 I've tried to contact the original author but unfortunately I did not get any answer. :(

Since yours is the main repo on GitHub I'd like to hear your opinion on pulling the following fixes and improvements:
- `mount` colourization
- `df` colourization
- fix `gcc` colourization of the `-o` option from spilling to the whole line

Let me know what you think about them.

Thanks!

### CODE REVIEW

**Comment by emanueleaina** [comment]
Hello, do you have any comments about the patch?

**Comment by pengwynn** [comment]
Sorry missed this one. Before I apply it, let me try to get in touch as well.

**Comment by emanueleaina** [comment]
Did you get any reply?

**Comment by emanueleaina** [comment]
@pengwynn any news from the original author?

**Comment by emanueleaina** [comment]
@pengwynn thanks!

I suppose you haven't got any reply too. :(

**Pull request merged**
